export enum AssetKeys {
  MAIN_SCENE_BACKGROUND = "MAIN_SCENE_BACKGROUND",
  DRAGON_ATLAS = "DRAGON_ATLAS",
  ENEMY_ATLAS = "ENEMY_ATLAS",
  FIRE = "FIRE",
  BULLET = "BULLET",
  BOOM = "BOOM",
  BOOM_SOUND = "BOOM_SOUND",
  THEME_SOUND = "THEME_SOUND",
}
